### ISSUE TITLE
use faker-russian with jruby

### ISSUE THREAD

**Issue by ovcharenkodi** [asiniy/faker-russian#6]
✗ gem list | grep faker-russian  
faker-russian (0.0.6)
 ✗ ruby -v
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26 +jit [darwin-x86_64]
✗ irb
:001 > require 'faker-russian'
LoadError: no such file to load -- faker-russian
	from org/jruby/RubyKernel.java:1065:in `require'
	from /Users/dmitry/.rvm/rubies/jruby-1.7.16/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from /Users/dmitry/.rvm/rubies/jruby-1.7.16/bin/irb:13:in `(root)'
 :002 > require 'faker'
 => true

**Comment by asiniy** [comment]
There is a windows... omg. I'm principial ubuntu user. That's why you need the help of windows user.

**Comment by asiniy** [comment]
Please wait for a few days, I'll try it on ubuntu

**Comment by ovcharenkodi** [comment]
This error is repeated on Mac OS X 10.10.2
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26 +jit   [darwin-x86_64]

**Comment by asiniy** [comment]
Same error on linux. 

It seems you need go deeper to jruby essentials. I'm not familiar with it. I'll try to find a time to fix it on the weekend.

**Comment by asiniy** [comment]
You can fasterize the solution by using experience of this issue: http://stackoverflow.com/questions/10833732/jruby-no-such-file-to-load

Just try it! If it works, feel free to modificate .travis.yml and send a pull request.

**Comment by asiniy** [comment]
Also try to

``` ruby
require 'faker/russian'
```

**Comment by ovcharenkodi** [comment]
I'm try:  require 'faker/russian'. But call Faker::Russian.* return errors

ui git:(develop) ✗ gem list | grep faker
faker (1.4.3)
faker-russian (0.0.6)
➜  ui git:(develop) ✗ irb                  
jruby-1.7.16 :001 > require 'faker'
 => true 
jruby-1.7.16 :002 > require 'faker/russian'
 => true 
jruby-1.7.16 :003 > Faker::Russian.inn
NoMethodError: undefined method `assert_valid_keys' for {}:Hash
	from /Users/dmitry/.rvm/gems/jruby-1.7.16@ui/gems/faker-russian-0.0.6/lib/faker/russian/inn.rb:5:in `inn'
	from (irb):3:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from /Users/dmitry/.rvm/rubies/jruby-1.7.16/bin/irb:13:in `(root)'
jruby-1.7.16 :004 >

**Comment by asiniy** [comment]
ok, so you can patch the gem for requiring activesupport special file

**Comment by dsulimchuk** [comment]
Hi, Issue is actual. Please fix it if you can. Thank a lot!

**Comment by asiniy** [comment]
Hi! Sorry, I don't have enough time to work on this

**Comment by atom1908** [comment]
Здравствуйте. А будут ли какие-нибудь обновления? Хотя бы чтобы работало на последней версии ruby/

**Comment by asiniy** [comment]
Will check in a few days

**Comment by atom1908** [comment]
> Will check in a few days

Есть новости?=)
